audiometria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('authentication/', include('authentication.urls')),
    path('exame_audiometria/', include('exame_audiometria.urls')),
    path('paciente/', include('paciente.urls')),
    path('reflexo_acustico/', include('reflexo_acustico.urls')),
    path('timpanograma/', include('timpanograma.urls')),
    path('classificacao_iprf/', include('classificacao_iprf.urls')),
    path('configuracao_audiometrica/', include('configuracao_audiometrica.urls')),
    path('grau_perda/', include('grau_perda.urls')),
    path('tipo_perda_auditiva/', include('tipo_perda_auditiva.urls')),
    path('admin/', admin.site.urls),
]

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    # ex: /paciente/
    path("", views.PacienteListView.as_view(), name="index"),

    # ex: /paciente/create/
    path("create", views.PacienteCreateView.as_view(), name="create"),

    # ex: /paciente/3/
    path("<int:pk>/", views.PacienteDetailView.as_view(), name="detail"),

    # ex: /paciente/update/3
    path("update/<int:pk>", views.PacienteUpdateView.as_view(), name="update"),

    # ex: /paciente/delete/3
    path("delete/<int:pk>", views.PacienteDeleteView.as_view(), name="delete"),
]

timpanograma/urls.py
from django.urls import path
from . import views

app_name = "timpanograma"

urlpatterns = [
    # ex: /timpanograma/
    path("", views.TimpanogramaListView.as_view(), name="index"),

    # ex: /timpanograma/create/
    path("create", views.TimpanogramaCreateView.as_view(), name="create"),

    # ex: /timpanograma/3/
    path("<int:pk>/", views.TimpanogramaDetailView.as_view(), name="detail"),

    # ex: /timpanograma/update/3
    path("update/<int:pk>", views.TimpanogramaUpdateView.as_view(), name="update"),

    # ex: /timpanograma/delete/3
    path("delete/<int:pk>", views.TimpanogramaDeleteView.as_view(), name="delete"),
]

timpanograma/models.py
from django.db import models


class Timpanograma(models.Model):
    tipo = models.CharField(max_length=10, null=False, blank=False, verbose_name='Tipo da curva')
    definicao = models.CharField(max_length=100, verbose_name='Definição')
    valor_referencia = models.CharField(max_length=200, null=True, blank=True, verbose_name='Valor de referência')

    def __str__(self):
        return self.tipo

timpanograma/views.py
from .models import Timpanograma
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.

class TimpanogramaListView(LoginRequiredMixin, ListView):
    model = Timpanograma
    paginate_by = 10
    template_name = 'timpanograma/index.html'
    context_object_name = 'object'
    ordering = ['id']
    login_url = "/authentication/login/"


class TimpanogramaDetailView(LoginRequiredMixin, DetailView):
    model = Timpanograma
    template_name = 'timpanograma/detail.html'
    login_url = "/authentication/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TimpanogramaCreateView(LoginRequiredMixin, CreateView):
    model = Timpanograma
    fields = ['tipo', 'definicao', 'valor_referencia']
    template_name = 'timpanograma/create.html'
    success_url = reverse_lazy('timpanograma:index')
    login_url = "/authentication/login/"


class TimpanogramaUpdateView(LoginRequiredMixin, UpdateView):
    model = Timpanograma
    fields = ['tipo', 'definicao', 'valor_referencia']
    template_name = 'timpanograma/update.html'
    success_url = reverse_lazy('timpanograma:index')
    login_url = "/authentication/login/"


class TimpanogramaDeleteView(LoginRequiredMixin, DeleteView):
    model = Timpanograma
    template_name = 'timpanograma/delete.html'
    success_url = reverse_lazy('timpanograma:index')
    login_url = "/authentication/login/"

timpanograma/templates/timpanograma/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Salvar" class="btn btn-primary">
                <a href="{% url 'timpanograma:index' %}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

timpanograma/templates/timpanograma/delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <p>Are you sure you want to delete "{{ object }}"?</p>
                <div id="div_id_tipo" class="mb-3">
                    <label for="id_tipo" class="form-label requiredField">Tipo</label>
                    <input type="text" name="tipo" value="{{ object.tipo }}" class="textinput form-control" id="id_tipo" readonly>
                </div>

                <div id="div_definicao" class="mb-3">
                    <label for="id_definicao" class="form-label requiredField">Definição</label>
                    <input type="text" name="definicao" value="{{ object.definicao }}" class="textinput form-control" id="id_definicao" readonly>
                </div>

                <div id="div_valor_referencia" class="mb-3">
                    <label for="id_valor_referencia" class="form-label requiredField">Valor de referência</label>
                    <input type="text" name="definicao" value="{{ object.valor_referencia }}" class="textinput form-control" id="id_valor_referencia" readonly>
                </div>

                <input type="submit" value="Deletar" class="btn btn-danger">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

timpanograma/templates/timpanograma/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <div id="div_id_tipo" class="mb-3">
                <label for="id_tipo" class="form-label requiredField">Tipo da curva</label>
                <input type="text" name="tipo" value="{{ object.tipo }}" class="textinput form-control" id="id_tipo" readonly>
            </div>

            <div id="div_definicao" class="mb-3">
                <label for="id_definicao" class="form-label requiredField">Definição</label>
                <input type="text" name="definicao" value="{{ object.definicao }}" class="textinput form-control" id="id_definicao" readonly>
            </div>

            <div id="div_valor_referencia" class="mb-3">
                <label for="id_valor_referencia" class="form-label requiredField">Valor de referência</label>
                <input type="text" name="definicao" value="{{ object.valor_referencia }}" class="textinput form-control" id="id_valor_referencia" readonly>
            </div>

            <a href="{% url 'timpanograma:index' %}" class="btn btn-light">Voltar</a>
        </div>
    </div>
{% endblock content %}

timpanograma/templates/timpanograma/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Timpanograma</h1>
    <p class="mb-4">Utilizada para avaliar o funcionamento e integridade da orelha média. A timpanometria convencional é realizada com o tom teste de 226Hz. Para lactentes e bebês, a literatura indica o tom com frequência mais alta (1000Hz).</p>

        <div class="card shadow mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col"><h5>Timpanograma</h5></div>
                    <div class="col col-lg-2">
                        <a type="button" class="btn btn-primary float-end" href="{% url 'timpanograma:create' %}"><i class="bi bi-plus"></i>Novo</a>
                    </div>
                </div>
            </div>
            {% if object %}
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Tipo da curva</th>
                            <th scope="col">Definição</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for config in object %}
                            <tr>
                                <td>{{ config.tipo }}</td>
                                <td>{{ config.definicao }}</td>
                                <td><a class="icon-link" href="{% url 'timpanograma:detail' config.id %}"><img src="{% static 'assets/bootstrap/icons/search.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'timpanograma:update' config.id %}"><img src="{% static 'assets/bootstrap/icons/pencil.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'timpanograma:delete' config.id %}"><img src="{% static 'assets/bootstrap/icons/trash.svg'%}"></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row mt-3">
                    <div class="col">
                        {% include 'partials/_pagination.html' %}
                    </div>
                </div>
            </div>
        {% else %}
        <p>No tipos are available.</p>
    {% endif %}
        </div>
{% endblock content %}

timpanograma/templates/timpanograma/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Atualizar" class="btn btn-primary">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}