audiometria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('authentication/', include('authentication.urls')),
    path('exame_audiometria/', include('exame_audiometria.urls')),
    path('paciente/', include('paciente.urls')),
    path('reflexo_acustico/', include('reflexo_acustico.urls')),
    path('timpanograma/', include('timpanograma.urls')),
    path('classificacao_iprf/', include('classificacao_iprf.urls')),
    path('configuracao_audiometrica/', include('configuracao_audiometrica.urls')),
    path('grau_perda/', include('grau_perda.urls')),
    path('tipo_perda_auditiva/', include('tipo_perda_auditiva.urls')),
    path('admin/', admin.site.urls),
]

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    # ex: /paciente/
    path("", views.PacienteListView.as_view(), name="index"),

    # ex: /paciente/create/
    path("create", views.PacienteCreateView.as_view(), name="create"),

    # ex: /paciente/3/
    path("<int:pk>/", views.PacienteDetailView.as_view(), name="detail"),

    # ex: /paciente/update/3
    path("update/<int:pk>", views.PacienteUpdateView.as_view(), name="update"),

    # ex: /paciente/delete/3
    path("delete/<int:pk>", views.PacienteDeleteView.as_view(), name="delete"),
]

paciente/models.py
from os import error
from django.forms import ValidationError
from django.db import models
from datetime import date, timedelta
from utils.validar_cpf import valida_cpf


class Paciente(models.Model):
    nome = models.CharField(max_length=80, blank=False, null=False)
    cpf = models.CharField(max_length=11, blank=False, null=False, verbose_name='CPF')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    endereco = models.CharField(max_length=100, blank=True, null=True, verbose_name='Endereço')
    #cidade
    #estado
    #celular
    #email

    def calcular_idade(self) -> int:
        idade = (date.today() - self.data_nascimento) // timedelta(days=365.2425)
        return idade

    def __str__(self):
        return self.nome

    def clean(self):
        error_messages = {}
        cpf_enviado = self.cpf
        cpf_salvo = None
        paciente = Paciente.objects.filter(cpf=cpf_enviado).first()

        if paciente:
            cpf_salvo = paciente.cpf

            if cpf_salvo is not None and self.pk != paciente.pk:
                error_messages['cpf'] = 'CPF já existe'

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um CPF válido'

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

paciente/forms.py
from django import forms


class PacienteForm(forms.Form):
    nome = forms.CharField(max_length=80, blank=False, null=False)
    cpf = forms.CharField(max_length=11, blank=False, null=False)
    data_nascimento = forms.DateField(verbose_name='Data de Nascimento')
    endereco = forms.CharField(max_length=100, blank=True, null=True)

paciente/views.py
from .models import Paciente
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class PacienteListView(LoginRequiredMixin, ListView):
    model = Paciente
    paginate_by = 10
    template_name = 'paciente/index.html'
    context_object_name = 'object'
    ordering = ['id']
    login_url = "/authentication/login/"


class PacienteDetailView(LoginRequiredMixin, DetailView):
    model = Paciente
    template_name = 'paciente/detail.html'
    login_url = "/authentication/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PacienteCreateView(LoginRequiredMixin, CreateView):
    model = Paciente
    fields = ['nome', 'cpf', 'data_nascimento', 'endereco']
    template_name = 'paciente/create.html'
    success_url = reverse_lazy('paciente:index')
    login_url = "/authentication/login/"


class PacienteUpdateView(LoginRequiredMixin, UpdateView):
    model = Paciente
    fields = ['nome', 'cpf', 'data_nascimento', 'endereco']
    template_name = 'paciente/update.html'
    success_url = reverse_lazy('paciente:index')
    login_url = "/authentication/login/"


class PacienteDeleteView(LoginRequiredMixin, DeleteView):
    model = Paciente
    template_name = 'paciente/delete.html'
    success_url = reverse_lazy('paciente:index')
    login_url = "/authentication/login/"

paciente/templates/paciente/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Salvar" class="btn btn-primary">
                <a href="{% url 'paciente:index' %}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

paciente/templates/paciente/delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <p>Are you sure you want to delete "{{ object }}"?</p>

                <div id="div_nome" class="mb-3">
                    <label for="id_nome" class="form-label requiredField">Nome</label>
                    <input type="text" name="nome" value="{{ object.nome }}" class="textinput form-control" id="id_nome" readonly>
                </div>

                <div id="div_cpf" class="mb-3">
                    <label for="id_cpf" class="form-label requiredField">CPF</label>
                    <input type="text" name="cpf" value="{{ object.cpf }}" class="textinput form-control" id="id_cpf" readonly>
                </div>

                <div id="div_data_nascimento" class="mb-3">
                    <label for="id_data_nascimento" class="form-label requiredField">Data de nascimento</label>
                    <input type="text" name="caracteristicas" value="{{ object.data_nascimento }}" class="textinput form-control" id="id_data_nascimento" readonly>
                </div>

                <div id="div_endereco" class="mb-3">
                    <label for="id_endereco" class="form-label requiredField">Endereço</label>
                    <input type="text" name="endereco" value="{{ object.endereco }}" class="textinput form-control" id="id_endereco" readonly>
                </div>

                <input type="submit" value="Deletar" class="btn btn-danger">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

paciente/templates/paciente/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
             <div id="div_nome" class="mb-3">
                <label for="id_nome" class="form-label requiredField">Nome</label>
                <input type="text" name="nome" value="{{ object.nome }}" class="textinput form-control" id="id_nome" readonly>
            </div>

            <div id="div_cpf" class="mb-3">
                <label for="id_cpf" class="form-label requiredField">CPF</label>
                <input type="text" name="cpf" value="{{ object.cpf }}" class="textinput form-control" id="id_cpf" readonly>
            </div>

            <div id="div_data_nascimento" class="mb-3">
                <label for="id_data_nascimento" class="form-label requiredField">Data de nascimento</label>
                <input type="text" name="caracteristicas" value="{{ object.data_nascimento }}" class="textinput form-control" id="id_data_nascimento" readonly>
            </div>

            <div id="div_endereco" class="mb-3">
                <label for="id_endereco" class="form-label requiredField">Endereço</label>
                <input type="text" name="endereco" value="{{ object.endereco }}" class="textinput form-control" id="id_endereco" readonly>
            </div>

            <a href="{% url 'paciente:index' %}" class="btn btn-light">Voltar</a>
        </div>
    </div>
{% endblock content %}

paciente/templates/paciente/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Paciente</h1>
    <p class="mb-4">Triagem inicial para pacientes.</p>

    <div class="card shadow mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col"><h5>Pacientes</h5></div>
                <div class="col col-lg-2">
                    <a type="button" class="btn btn-primary float-end" href="{% url 'paciente:create' %}"><i class="bi bi-plus"></i>Novo</a>
                </div>
            </div>
        </div>

        {% if object %}
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">CPF</th>
                            <th scope="col">Data de nascimento</th>
                            <th scope="col">Idade</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for config in object %}
                            <tr>
                                <td>{{ config.nome }}</td>
                                <td>{{ config.cpf }}</td>
                                <td>{{ config.data_nascimento }}</td>
                                <td>{{ config.calcular_idade }}</td>
                                <td><a class="icon-link" href="{% url 'paciente:detail' config.id %}"><img src="{% static 'assets/bootstrap/icons/search.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'paciente:update' config.id %}"><img src="{% static 'assets/bootstrap/icons/pencil.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'paciente:delete' config.id %}"><img src="{% static 'assets/bootstrap/icons/trash.svg'%}"></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row mt-3">
                    <div class="col">
                        {% include 'partials/_pagination.html' %}
                    </div>
                </div>
            </div>
        {% else %}
            <p>No tipos are available.</p>
        {% endif %}
    </div>
{% endblock content %}

paciente/templates/paciente/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Atualizar" class="btn btn-primary">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}