audiometria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('authentication/', include('authentication.urls')),
    path('exame_audiometria/', include('exame_audiometria.urls')),
    path('paciente/', include('paciente.urls')),
    path('reflexo_acustico/', include('reflexo_acustico.urls')),
    path('timpanograma/', include('timpanograma.urls')),
    path('classificacao_iprf/', include('classificacao_iprf.urls')),
    path('configuracao_audiometrica/', include('configuracao_audiometrica.urls')),
    path('grau_perda/', include('grau_perda.urls')),
    path('tipo_perda_auditiva/', include('tipo_perda_auditiva.urls')),
    path('admin/', admin.site.urls),
]

grau_perda/urls.py
from django.urls import path
from . import views

app_name = "grau_perda"

urlpatterns = [
    # ex: /grau_perda/
    path("", views.GrauPerdaListView.as_view(), name="index"),

    # ex: /grau_perda/create/
    path("create", views.GrauPerdaCreateView.as_view(), name="create"),

    # ex: /grau_perda/3/
    path("<int:pk>/", views.GrauPerdaDetailView.as_view(), name="detail"),

    # ex: /grau_perda/update/3
    path("update/<int:pk>", views.GrauPerdaUpdateView.as_view(), name="update"),

    # ex: /grau_perda/delete/3
    path("delete/<int:pk>", views.GrauPerdaDeleteView.as_view(), name="delete"),
]

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    # ex: /paciente/
    path("", views.PacienteListView.as_view(), name="index"),

    # ex: /paciente/create/
    path("create", views.PacienteCreateView.as_view(), name="create"),

    # ex: /paciente/3/
    path("<int:pk>/", views.PacienteDetailView.as_view(), name="detail"),

    # ex: /paciente/update/3
    path("update/<int:pk>", views.PacienteUpdateView.as_view(), name="update"),

    # ex: /paciente/delete/3
    path("delete/<int:pk>", views.PacienteDeleteView.as_view(), name="delete"),
]

grau_perda/models.py
from django.db import models

# Create your models here.


class GrauPerda(models.Model):
    grau_perda = models.CharField(max_length=40, null=False, blank=False, verbose_name='Grau de perda auditiva')
    media_frequencias = models.CharField(max_length=15, null=False, blank=False, verbose_name='Média entre as frequências de 500 Hz, 1 kHz, 2 kHz e 4 kHz')
    desempenho = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.grau_perda

grau_perda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import GrauPerda
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.


class GrauPerdaListView(LoginRequiredMixin, ListView):
    model = GrauPerda
    paginate_by = 10
    template_name = 'grau_perda/index.html'
    context_object_name = 'graus_list'
    ordering = ['id']
    login_url = "/authentication/login/"


class GrauPerdaDetailView(LoginRequiredMixin, DetailView):
    model = GrauPerda
    template_name = 'grau_perda/detail.html'
    login_url = "/authentication/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class GrauPerdaCreateView(LoginRequiredMixin, CreateView):
    model = GrauPerda
    fields = ['grau_perda', 'media_frequencias', 'desempenho']
    template_name = 'grau_perda/create.html'
    success_url = reverse_lazy('grau_perda:index')
    login_url = "/authentication/login/"


class GrauPerdaUpdateView(LoginRequiredMixin, UpdateView):
    model = GrauPerda
    fields = ['grau_perda', 'media_frequencias', 'desempenho']
    template_name = 'grau_perda/update.html'
    success_url = reverse_lazy('grau_perda:index')
    login_url = "/authentication/login/"


class GrauPerdaDeleteView(LoginRequiredMixin, DeleteView):
    model = GrauPerda
    template_name = 'grau_perda/delete.html'
    success_url = reverse_lazy('grau_perda:index')
    login_url = "/authentication/login/"

grau_perda/templates/grau_perda/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Salvar" class="btn btn-primary">
                <a href="{% url 'grau_perda:index' %}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

grau_perda/templates/grau_perda/delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <p>Are you sure you want to delete "{{ object }}"?</p>
                <div id="div_id_grau_perda" class="mb-3">
                    <label for="id_grau_perda" class="form-label requiredField">Grau de perda auditiva</label>
                    <input type="text" name="grau_perda" value="{{ object.grau_perda }}" class="textinput form-control" id="id_grau_perda" readonly>
                </div>

                <div id="div_media_frequencias" class="mb-3">
                    <label for="id_media_frequencias" class="form-label requiredField">Características</label>
                    <input type="text" name="media_frequencias" value="{{ object.media_frequencias }}" class="textinput form-control" id="id_media_frequencias" readonly>
                </div>

                <div id="div_desempenho" class="mb-3">
                    <label for="id_desempenho" class="form-label requiredField">Características</label>
                    <input type="text" name="desempenho" value="{{ object.desempenho }}" class="textinput form-control" id="id_desempenho" readonly>
                </div>

                <input type="submit" value="Deletar" class="btn btn-danger">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

grau_perda/templates/grau_perda/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <div id="div_id_grau_perda" class="mb-3">
                <label for="id_grau_perda" class="form-label requiredField">Grau de perda auditiva</label>
                <input type="text" name="grau_perda" value="{{ object.grau_perda }}" class="textinput form-control" id="id_grau_perda" readonly>
            </div>

            <div id="div_media_frequencias" class="mb-3">
                <label for="id_media_frequencias" class="form-label requiredField">Características</label>
                <input type="text" name="media_frequencias" value="{{ object.media_frequencias }}" class="textinput form-control" id="id_media_frequencias" readonly>
            </div>

            <div id="div_desempenho" class="mb-3">
                <label for="id_desempenho" class="form-label requiredField">Características</label>
                <input type="text" name="desempenho" value="{{ object.desempenho }}" class="textinput form-control" id="id_desempenho" readonly>
            </div>

            <a href="{% url 'grau_perda:index' %}" class="btn btn-light">Voltar</a>
        </div>
    </div>
{% endblock content %}

grau_perda/templates/grau_perda/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Classificação do grau da perda auditiva</h1>
    <p class="mb-4">Para a classificação da perda auditiva quanto ao grau, são encontradas na literatura diversas
        recomendações. A Organização Mundial de Saúde (2020) publicou material intitulado Basic Ear and Hearing Care
        Resource no qual utilizou a classificação dos Graus de Deficiência Auditiva REVISADA (Quadro 6), ou seja,
        considerou o limiar de 20 dB como sendo uma perda auditiva de grau leve e recomenda que seja vista juntamente
        com a Classificação Internacional de Funcionalidade (CIF).</p>

    <div class="card shadow mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col"><h5>Classificação do grau da perda auditiva</h5></div>
                <div class="col col-lg-2">
                    <a type="button" class="btn btn-primary float-end" href="{% url 'grau_perda:create' %}"><i class="bi bi-plus"></i>Novo</a>
                </div>
            </div>
        </div>

        {% if graus_list %}
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Grau de perda auditiva</th>
                            <th scope="col">Média entre as frequências de 500 Hz, 1 kHz, 2 kHz e 4 kHz</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for grau in graus_list %}
                            <tr>
                                <td>{{ grau.grau_perda }}</td>
                                <td>{{ grau.media_frequencias }}</td>
                                <td><a class="icon-link" href="{% url 'grau_perda:detail' grau.id %}"><img src="{% static 'assets/bootstrap/icons/search.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'grau_perda:update' grau.id %}"><img src="{% static 'assets/bootstrap/icons/pencil.svg'%}"></a></td>
                                <td><a class="icon-link" href="{% url 'grau_perda:delete' grau.id %}"><img src="{% static 'assets/bootstrap/icons/trash.svg'%}"></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row mt-3">
                    <div class="col">
                        {% include 'partials/_pagination.html' %}
                    </div>
                </div>
            </div>
        {% else %}
            <p>No tipos are available.</p>
        {% endif %}
    </div>
{% endblock content %}

grau_perda/templates/grau_perda/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Atualizar" class="btn btn-primary">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}