audiometria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('authentication/', include('authentication.urls')),
    path('exame_audiometria/', include('exame_audiometria.urls')),
    path('paciente/', include('paciente.urls')),
    path('reflexo_acustico/', include('reflexo_acustico.urls')),
    path('timpanograma/', include('timpanograma.urls')),
    path('classificacao_iprf/', include('classificacao_iprf.urls')),
    path('configuracao_audiometrica/', include('configuracao_audiometrica.urls')),
    path('grau_perda/', include('grau_perda.urls')),
    path('tipo_perda_auditiva/', include('tipo_perda_auditiva.urls')),
    path('admin/', admin.site.urls),
]

exame_audiometria/urls.py
from django.urls import path
from . import views

app_name = "exame_audiometria"

urlpatterns = [
    # ex: /exame_audiometria/
    path("", views.ExameAudiometriaListView.as_view(), name="index"),

    # ex: /exame_audiometria/create/
    path("create", views.ExameAudiometriaCreateView.as_view(), name="create"),

    # ex: /exame_audiometria/3/
    path("<int:pk>/", views.ExameAudiometriaDetailView.as_view(), name="detail"),

    # ex: /exame_audiometria/update/3
    path("update/<int:pk>", views.exame_audiometria_update, name="update"),
    #path("update/<int:pk>", views.ExameAudiometriaUpdateView.as_view(), name="update"),

    # ex: /exame_audiometria/delete/3
    path("delete/<int:pk>", views.ExameAudiometriaDeleteView.as_view(), name="delete"),

    path("export-pdf", views.export_pdf, name="export-pdf"),

    path("search/", views.Search.as_view(), name="search"),
]

paciente/urls.py
from django.urls import path
from . import views

app_name = "paciente"

urlpatterns = [
    # ex: /paciente/
    path("", views.PacienteListView.as_view(), name="index"),

    # ex: /paciente/create/
    path("create", views.PacienteCreateView.as_view(), name="create"),

    # ex: /paciente/3/
    path("<int:pk>/", views.PacienteDetailView.as_view(), name="detail"),

    # ex: /paciente/update/3
    path("update/<int:pk>", views.PacienteUpdateView.as_view(), name="update"),

    # ex: /paciente/delete/3
    path("delete/<int:pk>", views.PacienteDeleteView.as_view(), name="delete"),
]

reflexo_acustico/urls.py
from django.urls import path
from . import views

app_name = "reflexo_acustico"

urlpatterns = [
    # ex: /reflexo_acustico/
    path("", views.ReflexoAcusticoListView.as_view(), name="index"),

    # ex: /reflexo_acustico/create/
    path("create", views.ReflexoAcusticoCreateView.as_view(), name="create"),

    # ex: /reflexo_acustico/3/
    path("<int:pk>/", views.ReflexoAcusticoDetailView.as_view(), name="detail"),

    # ex: /reflexo_acustico/update/3
    path("update/<int:pk>", views.ReflexoAcusticoUpdateView.as_view(), name="update"),

    # ex: /reflexo_acustico/delete/3
    path("delete/<int:pk>", views.ReflexoAcusticoDeleteView.as_view(), name="delete"),
]

exame_audiometria/models.py
from django.db import models
from paciente.models import Paciente
from django.utils.translation import gettext_lazy as _


class ExameAudiometria(models.Model):
    class TipoExame(models.TextChoices):
        ADMISSIONAL = 'AD', _('Admissional')
        PERIODICO = 'PE', _('Periódico')
        DEMISSIONAL = "DE", _("Demissional")
        SEXTO_MES = 'SM', _('6º Mês')
        MUDANCA_FUNCAO = 'MF', _('Mudança de Função')
        RETORNO_TRABALHO = 'RT', _('Retorno ao Trabalho')
        __empty__ = _("(Selecione o tipo do exame)")

    class DiagnosticoNosologico(models.TextChoices):
        NORMAL = 'NO', _('Normal')
        PAO = 'PA', _('PAO')
        PANO = "PN", _("PANO")
        __empty__ = _("(Selecione o diagnóstico nosológico)")

    class DiagnosticoEvolutivo(models.TextChoices):
        NORMAL = 'NO', _('Normal')
        ESTAVEL = 'ES', _('Estável')
        SUGESTIVO_PAINPSE = "SP", _("Sugestivo de Painpse")
        AGRAVAMENTO_PAINPSE = 'AP', _('Agravamento de Painpse')
        DESENCADEAMENTO_PAINPSE = 'DP', _('Desencadeamento  de Painpse')
        NAO_SUGESTIVO_PAINPSE = 'NP', _('Não Sugestivo  de Painpse')
        __empty__ = _("(Selecione o diagnóstico evolutivo)")

    paciente = models.ForeignKey(Paciente, blank=False, null=False, on_delete=models.PROTECT)
    data_exame = models.DateTimeField(blank=False, null=False, verbose_name='Data do exame')
    tipo_exame = models.CharField(max_length=2, choices=TipoExame, blank=False, null=False)

    # Ouvido direito - Vias aéreas
    od_via_aerea_250 = models.SmallIntegerField(verbose_name='250')
    od_via_aerea_500 = models.SmallIntegerField(verbose_name='500')
    od_via_aerea_1000 = models.SmallIntegerField(verbose_name='1000')
    od_via_aerea_2000 = models.SmallIntegerField(verbose_name='2000')
    od_via_aerea_3000 = models.SmallIntegerField(verbose_name='3000')
    od_via_aerea_4000 = models.SmallIntegerField(verbose_name='4000')
    od_via_aerea_6000 = models.SmallIntegerField(verbose_name='6000')
    od_via_aerea_8000 = models.SmallIntegerField(verbose_name='8000')

    # Ouvido direito - Vias ósseas
    od_via_ossea_250 = models.SmallIntegerField(verbose_name='250')
    od_via_ossea_500 = models.SmallIntegerField(verbose_name='500')
    od_via_ossea_1000 = models.SmallIntegerField(verbose_name='1000')
    od_via_ossea_2000 = models.SmallIntegerField(verbose_name='2000')
    od_via_ossea_3000 = models.SmallIntegerField(verbose_name='3000')
    od_via_ossea_4000 = models.SmallIntegerField(verbose_name='4000')
    od_via_ossea_6000 = models.SmallIntegerField(verbose_name='6000')
    od_via_ossea_8000 = models.SmallIntegerField(verbose_name='8000')

    od_sequencial_referencial = models.CharField(max_length=1, choices=[('S', 'Sequencial'), ('R', 'Referencial')], verbose_name='Sequencial/Referencial')
    od_diagnostico_nosologico = models.CharField(max_length=2, choices=DiagnosticoNosologico, verbose_name='Diagnóstico nosológico')
    od_diagnostico_evolutivo =  models.CharField(max_length=2, choices=DiagnosticoEvolutivo, verbose_name='Diagnóstico evolutivo')

    # Ouvido esquerdo - Vias aéreas
    oe_via_aerea_250 = models.SmallIntegerField(verbose_name='250')
    oe_via_aerea_500 = models.SmallIntegerField(verbose_name='500')
    oe_via_aerea_1000 = models.SmallIntegerField(verbose_name='1000')
    oe_via_aerea_2000 = models.SmallIntegerField(verbose_name='2000')
    oe_via_aerea_3000 = models.SmallIntegerField(verbose_name='3000')
    oe_via_aerea_4000 = models.SmallIntegerField(verbose_name='4000')
    oe_via_aerea_6000 = models.SmallIntegerField(verbose_name='6000')
    oe_via_aerea_8000 = models.SmallIntegerField(verbose_name='8000')

    # Ouvido esquerdo - Vias ósseas
    oe_via_ossea_250 = models.SmallIntegerField(verbose_name='250')
    oe_via_ossea_500 = models.SmallIntegerField(verbose_name='500')
    oe_via_ossea_1000 = models.SmallIntegerField(verbose_name='1000')
    oe_via_ossea_2000 = models.SmallIntegerField(verbose_name='2000')
    oe_via_ossea_3000 = models.SmallIntegerField(verbose_name='3000')
    oe_via_ossea_4000 = models.SmallIntegerField(verbose_name='4000')
    oe_via_ossea_6000 = models.SmallIntegerField(verbose_name='6000')
    oe_via_ossea_8000 = models.SmallIntegerField(verbose_name='8000')

    oe_sequencial_referencial = models.CharField(max_length=1, choices=[('S', 'Sequencial'), ('R', 'Referencial')], verbose_name='Sequencial/Referencial')
    oe_diagnostico_nosologico = models.CharField(max_length=2, choices=DiagnosticoNosologico, verbose_name='Diagnóstico nosológico')
    oe_diagnostico_evolutivo = models.CharField(max_length=2, choices=DiagnosticoEvolutivo, verbose_name='Diagnóstico evolutivo')

reflexo_acustico/models.py
from django.db import models


class ReflexoAcustico(models.Model):
    tipo = models.CharField(max_length=1, choices=[('P', 'Presente'), ('A', 'Ausente')])
    descricao = models.CharField(max_length=80, null=False, blank=False, verbose_name='Descrição')
    caracteristicas = models.CharField(max_length=200, null=True, blank=True, verbose_name='Características')

    def __str__(self):
        return self.descricao

timpanograma/models.py
from django.db import models


class Timpanograma(models.Model):
    tipo = models.CharField(max_length=10, null=False, blank=False, verbose_name='Tipo da curva')
    definicao = models.CharField(max_length=100, verbose_name='Definição')
    valor_referencia = models.CharField(max_length=200, null=True, blank=True, verbose_name='Valor de referência')

    def __str__(self):
        return self.tipo

exame_audiometria/forms.py
from django import forms
from .models import ExameAudiometria


class ExameAudiometriaForm(forms.ModelForm):
    class Meta:
        model = ExameAudiometria
        fields = '__all__'

exame_audiometria/views.py
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from .models import ExameAudiometria
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from paciente.models import Paciente
from .forms import ExameAudiometriaForm
from datetime import datetime
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration
from django.db.models import Q, DateField
import tempfile
from django.template.loader import render_to_string
import  os
import logging


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ExameAudiometriaListView(LoginRequiredMixin, ListView):
    model = ExameAudiometria
    paginate_by = 10
    template_name = 'exame_audiometria/index.html'
    context_object_name = 'object'
    ordering = ['id']
    login_url = "/authentication/login/"


class ExameAudiometriaDetailView(LoginRequiredMixin, DetailView):
    model = ExameAudiometria
    template_name = 'exame_audiometria/detail.html'
    login_url = "/authentication/login/"


class ExameAudiometriaCreateView(LoginRequiredMixin, CreateView):
    model = ExameAudiometria
    login_url = "/authentication/login/"
    context_object_name = 'object'
    fields = '__all__'
    template_name = 'exame_audiometria/create.html'
    success_url = reverse_lazy('exame_audiometria:index')

    def get_context_data(self, **kwargs):
        pacientes_list = Paciente.objects.all()
        context = super(ExameAudiometriaCreateView, self).get_context_data(**kwargs)
        context['pacientes_list'] = pacientes_list
        return context

@login_required(login_url="/authentication/login/")
def exame_audiometria_update(request, pk):
    exame_audiometria = get_object_or_404(ExameAudiometria, pk=pk)

    if request.method == 'POST':
        form = ExameAudiometriaForm(request.POST, instance=exame_audiometria)
        if form.is_valid():
            form.save()
            return redirect('exame_audiometria:index')
    return render(request, 'exame_audiometria/update.html', {'object': exame_audiometria})


class ExameAudiometriaDeleteView(LoginRequiredMixin, DeleteView):
    model = ExameAudiometria
    template_name = 'exame_audiometria/delete.html'
    success_url = reverse_lazy('exame_audiometria:index')
    login_url = "/authentication/login/"


def export_pdf(request):
    exames_audiometria = ExameAudiometria.objects.all()
    total = ExameAudiometria.objects.count()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; attachment; filename=ExamesAudiometria' + str(datetime.now()) + '.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    html_string = render_to_string('exame_audiometria/pdf-output.html', {'exames_audiometria': exames_audiometria, 'total': total})
    html = HTML(string=html_string)

    font_config = FontConfiguration()
    css = CSS(os.path.join(settings.BASE_DIR, 'exame_audiometria/templates/exame_audiometria/report.css'), font_config=font_config)

    result = html.write_pdf(stylesheets=[css], font_config=font_config)

    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return  response

class Search(ExameAudiometriaListView):
    def get_queryset(self, *args, **kwargs):
        search = self.request.GET.get('search')
        data_exame_search = datetime.strptime(self.request.GET.get('data_exame_search'), '%Y-%d-%m').date()
        qs = super().get_queryset(*args, **kwargs)

        #if not search:
            #return qs

        qs = qs.filter(
            Q(paciente__nome__icontains=search) |
            Q(data_exame__date=data_exame_search)
        )

        #logger.info(qs.query)
        return qs

exame_audiometria/templates/exame_audiometria/delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                <p>Are you sure you want to delete "{{ object }}"?</p>

                <div id="div_id_tipo" class="mb-3">
                    <label for="id_tipo" class="form-label requiredField">Tipo</label>
                    <input type="text" name="tipo" value="{{ object.tipo }}" class="textinput form-control" id="id_tipo" readonly>
                </div>

                <div id="div_descricao" class="mb-3">
                    <label for="id_descricao" class="form-label requiredField">Descrição</label>
                    <input type="text" name="descricao" value="{{ object.descricao }}" class="textinput form-control" id="id_descricao" readonly>
                </div>

                <div id="div_caracteristicas" class="mb-3">
                    <label for="id_caracteristicas" class="form-label requiredField">Características</label>
                    <input type="text" name="caracteristicas" value="{{ object.caracteristicas }}" class="textinput form-control" id="id_caracteristicas" readonly>
                </div>

                <input type="submit" value="Deletar" class="btn btn-danger">
                <a href="{{ view.get_success_url }}" class="btn btn-light">Voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

exame_audiometria/templates/exame_audiometria/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <div id="div_id_tipo" class="mb-3">
                <label for="id_tipo" class="form-label requiredField">Tipo</label>
                <input type="text" name="tipo" value="{{ object.tipo }}" class="textinput form-control" id="id_tipo" readonly>
            </div>

            <div id="div_descricao" class="mb-3">
                <label for="id_descricao" class="form-label requiredField">Descrição</label>
                <input type="text" name="descricao" value="{{ object.descricao }}" class="textinput form-control" id="id_descricao" readonly>
            </div>

            <div id="div_caracteristicas" class="mb-3">
                <label for="id_caracteristicas" class="form-label requiredField">Características</label>
                <input type="text" name="caracteristicas" value="{{ object.caracteristicas }}" class="textinput form-control" id="id_caracteristicas" readonly>
            </div>

            <a href="{% url 'reflexo_acustico:index' %}" class="btn btn-light">Voltar</a>
        </div>
    </div>
{% endblock content %}

exame_audiometria/templates/exame_audiometria/pdf-output.html
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <title>Report</title>
    <meta name="description" content="Report example">
</head>

{% for exame_audiometria in exames_audiometria %}
<body>

<article id="skills">
    <h3 id="typography-title">Exame de Audiometria</h3>

    <section id="table-content">
        <p>
            <strong>Nome:</strong> {{ exame_audiometria.paciente }}
            <br>
            <strong>Data de nascimento:</strong> {{ exame_audiometria.paciente.data_nascimento|date:'SHORT_DATE_FORMAT' }}
            <br>
            <strong>Data do exame:</strong> {{ exame_audiometria.data_exame|date:'SHORT_DATETIME_FORMAT' }}
            <br>
            <strong>Tipo do exame:</strong> {{ exame_audiometria.get_tipo_exame_display }}
        </p>
    </section>
</article>

<article id="typography">
    <section id="figures">
        <h4>Ouvido Direito</h4>
    </section>


    <h5>Vias Aéreas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.od_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_500 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_1000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_2000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_3000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_4000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_6000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_8000 }}</td>
        </tr>
    </table>

    <h5>Vias Ósseas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.od_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_500 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_1000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_2000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_3000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_4000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_6000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_8000 }}</td>
        </tr>
    </table>
    <br>

    <table style="width:100%">
        <tr>
            <th>Sequencial/Referencial</th>
            <th>Diagnóstico nosológico</th>
            <th>Diagnóstico evolutivo</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.get_od_sequencial_referencial_display }} </td>
            <td> {{ exame_audiometria.get_od_diagnostico_nosologico_display }} </td>
            <td> {{ exame_audiometria.get_od_diagnostico_evolutivo_display }} </td>
        </tr>
    </table>

    <section>
        <h4>Ouvido Esquerdo</h4>
    </section>

    <h5>Vias Aéreas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.oe_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_500 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_1000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_2000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_3000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_4000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_6000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_8000 }}</td>
        </tr>
    </table>

    <h5>Vias Ósseas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.oe_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_500 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_1000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_2000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_3000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_4000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_6000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_8000 }}</td>
        </tr>
    </table>

    <table style="width:100%">
        <tr>
            <th>Sequencial/Referencial</th>
            <th>Diagnóstico nosológico</th>
            <th>Diagnóstico evolutivo</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.get_oe_sequencial_referencial_display }} </td>
            <td> {{ exame_audiometria.get_oe_diagnostico_nosologico_display }} </td>
            <td> {{ exame_audiometria.get_oe_diagnostico_evolutivo_display }} </td>
        </tr>
    </table>
</article>


</body>
{% endfor %}
</html>

exame_audiometria/templates/exame_audiometria/report (Copy).html
<html>
  <head>
    <meta charset="utf-8">
    <link href="./report.css" rel="stylesheet">
    <title>Report</title>
    <meta name="description" content="Report example">
  </head>

  <body>

<article id="skills">
    <h3 id="typography-title">Exame de Audiometria</h3>

    <section id="table-content">
        <p>
            <strong>Nome:</strong> {{ exame_audiometria.paciente }}
            <br>
            <strong>Data de nascimento:</strong> {{ exame_audiometria.paciente.data_nascimento|date:'SHORT_DATE_FORMAT' }}
            <br>
            <strong>Data do exame:</strong> {{ exame_audiometria.data_exame|date:'SHORT_DATETIME_FORMAT' }}
            <br>
            <strong>Tipo do exame:</strong> {{ exame_audiometria.get_tipo_exame_display }}
        </p>
    </section>
</article>

<article id="typography">
    <section id="figures">
        <h4>Ouvido Direito</h4>
    </section>


    <h5>Vias Aéreas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.od_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_500 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_1000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_2000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_3000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_4000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_6000 }}</td>
            <td> {{ exame_audiometria.od_via_aerea_8000 }}</td>
        </tr>
    </table>

    <h5>Vias Ósseas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.od_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_500 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_1000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_2000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_3000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_4000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_6000 }}</td>
            <td> {{ exame_audiometria.od_via_ossea_8000 }}</td>
        </tr>
    </table>
    <br>

    <table style="width:100%">
        <tr>
            <th>Sequencial/Referencial</th>
            <th>Diagnóstico nosológico</th>
            <th>Diagnóstico evolutivo</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.get_od_sequencial_referencial_display }} </td>
            <td> {{ exame_audiometria.get_od_diagnostico_nosologico_display }} </td>
            <td> {{ exame_audiometria.get_od_diagnostico_evolutivo_display }} </td>
        </tr>
    </table>

    <section>
        <h4>Ouvido Esquerdo</h4>
    </section>

    <h5>Vias Aéreas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.oe_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_500 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_1000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_2000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_3000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_4000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_6000 }}</td>
            <td> {{ exame_audiometria.oe_via_aerea_8000 }}</td>
        </tr>
    </table>

    <h5>Vias Ósseas</h5>

    <table style="width:100%">
        <tr>
            <th>250</th>
            <th>500</th>
            <th>1000</th>
            <th>2000</th>
            <th>3000</th>
            <th>4000</th>
            <th>6000</th>
            <th>8000</th>
            <th>Hz</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.oe_via_aerea_250 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_500 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_1000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_2000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_3000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_4000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_6000 }}</td>
            <td> {{ exame_audiometria.oe_via_ossea_8000 }}</td>
        </tr>
    </table>

    <table style="width:100%">
        <tr>
            <th>Sequencial/Referencial</th>
            <th>Diagnóstico nosológico</th>
            <th>Diagnóstico evolutivo</th>
        </tr>
        <tr>
            <td> {{ exame_audiometria.get_oe_sequencial_referencial_display }} </td>
            <td> {{ exame_audiometria.get_oe_diagnostico_nosologico_display }} </td>
            <td> {{ exame_audiometria.get_oe_diagnostico_evolutivo_display }} </td>
        </tr>
    </table>
</article>

  </body>
</html>